### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by StefanKopieczek** [StefanKopieczek/gossip#14]
Logging library should log a timestamp and a thread ID.

**Comment by DiscoViking** [comment]
Not sure there's any way to get a thread ID.
I had a little browse online and couldn't find anything except a bunch of people saying you're not supposed to access it. :(

**Comment by DiscoViking** [comment]
http://stackoverflow.com/questions/19115273/looking-for-a-call-or-thread-id-to-use-for-logging

**Comment by DiscoViking** [comment]
Seeing as it looks like a thread-ID isn't possible.  Propose closing now that timestamps are done.

Close if you agree. :)

**Comment by StefanKopieczek** [comment]
Bah, what a shame :(  Yes, I think you're right, although I don't buy their justification, and the IDs are clearly available to the runtime since it can print stacktraces.

But yes, nothing more we can do here.
