### ISSUE TITLE
Gossip re-orders header and URI params

### ISSUE THREAD

**Issue by StefanKopieczek** [StefanKopieczek/gossip#19]
* If we are acting as a transparent proxy, we may reorder header params and URI params when we forward messages.
* Gossip processes header and URI params in an undefined order.
* String representations of SIP messages received by gossip may show params in a diferent order to that received off the wire.

This is because the Params object that stores them holds them in a map, which doesn't have a defined iteration order. 

Fixer should uncomment the broken stringify tests.

**Comment by StefanKopieczek** [comment]
I think this is a dupe of your issue #3. Close of you agree.

**Comment by DiscoViking** [comment]
Yes.
