### ISSUE TITLE
Display name fails to parse

### ISSUE THREAD

**Issue by StefanKopieczek** [StefanKopieczek/gossip#26]
The parser rejects the following:

    From: "John"<sip:foo@bar.com>

and

    To: Jane<sip:bar@foo.com>

... However,  having a space before the angle bracket should not be compulsory, per rfc 3261 20.10.

**Comment by matlab2000** [comment]
I just find this bug too. as the BNF by sip spec,  at last , i add 
	firstSpace := findAnyUnescaped(addressText, c_ABNF_WS, quotes_delim, angles_delim)
       //add start
	if firstSpace==-1 &&  (firstAngleBracket!=-1 && addressText[firstAngleBracket-1]=='"') {
		firstSpace=firstAngleBracket
	}
       //add end
to hack it

**Comment by StefanKopieczek** [comment]
Fixed by @DiscoViking in 90ad88d60ab57af45bb897724eb60593440170d1
