### ISSUE TITLE
在生产环境可以使用吗?

### ISSUE THREAD

**Issue by shizenghua** [StefanKopieczek/gossip#39]
在生产环境可以使用吗?

**Comment by StefanKopieczek** [comment]
Hi shizenghua, 

No, I wouldn't consider gossip production quality right now. 

The main reason is that we haven't carried out extensive load or scaling testing, or tested its resilience to adverse conditions. 

You might be able to use it as a starting point for your own development, but I wouldn't deploy it as-is in a high-availability environment without doing thorough testing first. 

Hope that answers your question. 

(Sorry I couldn't reply in Chinese. Hope this response makes sense to you!) 

Stefan
