### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by msanterre** [StefanKopieczek/gossip#41]
I'd like to use this library in one of my projects, but it looks quite abandoned with no licensing. 

Is there a plan to do any more work on this?

**Comment by lylepratt** [comment]
+1

**Comment by cwysong85** [comment]
+1

**Comment by SillyFlame** [comment]
+1

**Comment by SillyFlame** [comment]
++1

**Comment by StefanKopieczek** [comment]
Hey folks,

Sorry for the slow reply here, and thanks for the interest!

Gossip is licensed under the LGPL v2.1 per the license file in the root directory of the project: https://github.com/StefanKopieczek/gossip/blob/master/LICENSE. Feel free to use it however you like, within the provisions of the license.

As you can see we haven't had a tonne of time to put into the project in the last year - DiscoViking and myself have much less availability to work on side projects than when we started Gossip, and while we're not abandoning it, it's unlikely to see large amounts of new work.

We welcome PRs and would be happy to review any changes you would like to submit. Also feel free to file issues, though it might take us a while to get to them.

Thanks again for your interest in the project – we hope you'll get something out of it :)
